import { Task, TaskRunOptions } from '@src';

export default async (task: Task, { force, from }: TaskRunOptions = {}): Promise<void> => {
  // const pz_args = ["Puzzle Token", "PUZZLE", "355000000000000000000000"];
  // const weth_args = ["Wrapped Ether", "WETH", "355000000000000000000000"];
  // const swopfi_args = ["Swopfi Token", "SWOP", "355000000000000000000000"];
  // const wx_args = ["WX Token", "WX", "355000000000000000000000"];
  const usdt_args = ["USDT test Token", "pUSDTt", 6, "1000000000000"];
  const usdc_args = ["USDC test Token", "pUSDCt", 6, "1000000000000"];
  const wbtc_args = ["WBTC test Token", "wBTCt", 18, "1000000000000000000000"];
  const weth_args = ["WETH test Token", "wETHt", 18, "100000000000000000000000"];
  const upuzzle_args = ["UPUZZLE test Token", "uPuzzlet", 18, "100000000000000000000000"];
  // const pz = await task.deployAndVerify('CustomToken', pz_args, from, force);
  // console.log("Deployed Puzzle:", pz.address);
  // const weth = await task.deployAndVerify('CustomToken', weth_args, from, force);
  // console.log("Deployed WETH:", weth.address);
  // const swopfi = await task.deployAndVerify('CustomToken', swopfi_args, from, force);
  // console.log("Deployed SWOPFI:", swopfi.address);
  // const wx = await task.deployAndVerify('CustomToken', wx_args, from, force);
  // console.log("Deployed WX:", wx.address);
  const usdt = await task.deployAndVerify('CustomToken', usdt_args, from, force);
  console.log("Deployed USDT:", usdt.address);
  const usdc = await task.deployAndVerify('CustomToken', usdc_args, from, force);
  console.log("Deployed USDC:", usdc.address);
  const btc = await task.deployAndVerify('CustomToken', wbtc_args, from, force);
  console.log("Deployed BTC:", btc.address);
  const eth = await task.deployAndVerify('CustomToken', weth_args, from, force);
  console.log("Deployed ETH:", eth.address);
  const puzzle = await task.deployAndVerify('CustomToken', upuzzle_args, from, force);
  console.log("Deployed UPUZZLE:", puzzle.address);
};
